[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Note: This is for frontend deployment only
# Backend server needs to be deployed separately to a service like:
# - Railway
# - Heroku  
# - DigitalOcean
# - AWS EC2
# - VPS with Node.js support
</netlify.toml>